export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A serene landscape of floating islands with waterfalls cascading into the clouds, digital art",
  "A man exploring the vibrant streets of a futuristic Kowloon at night, illuminated by holographic neon signs",
  "A steampunk airship sailing through a sky filled with colorful hot air balloons",
  "A magical library with books that float and glow, surrounded by enchanted creatures",
  "A cyberpunk cityscape with towering skyscrapers and flying cars, digital art",
  "A whimsical tea party attended by anthropomorphic animals in a lush forest, watercolor",
  "A giant robot helping farmers in a rice field, anime style",
  "A surreal underwater city with glowing jellyfish and coral skyscrapers",
  "A Viking ship sailing through a stormy sea under the northern lights, oil painting",
  "A futuristic train speeding through a desert with a backdrop of massive sand dunes, digital art",
  "A cozy cabin in the woods during a snowy winter night, with smoke rising from the chimney, digital art",
  "A dragon curled around a castle tower, guarding a treasure hoard, fantasy art",
  "A bustling alien marketplace with creatures from different planets trading goods, sci-fi art",
  "A photo of a robot barista serving coffee in a futuristic café",
  "A surreal dreamscape of floating clocks and melting landscapes, inspired by Salvador Dalí",
  "A group of astronauts playing soccer on the surface of Mars, photography",
  "A futuristic city with vertical gardens and solar-powered skyscrapers, digital art",
  "A mythical phoenix rising from the ashes in a fiery explosion, digital art",
  "A whimsical candy land with rivers of chocolate and mountains of ice cream, digital art",
  "A knight in shining armor battling a dragon in a stormy sky, fantasy art",
  "A photo of a futuristic motorcycle speeding through a neon-lit city at night",
  "A serene Japanese garden with cherry blossoms and a koi pond, watercolor",
  "A space station orbiting a colorful gas giant, sci-fi art",
  "A photo of a cat wearing a spacesuit floating in zero gravity inside a spaceship",
  "A fantasy castle built into the side of a mountain, surrounded by clouds, digital art",
  "A surreal painting of a tree with glowing fruit in a dark forest",
  "A futuristic robot chef preparing a gourmet meal in a high-tech kitchen",
  "A photo of a glowing bioluminescent forest at night, with fireflies lighting the way",
  "A whimsical hot air balloon festival in a fantasy world with floating islands",
  "A cyberpunk samurai standing on a rooftop overlooking a neon-lit city, digital art",
  "A magical portal opening in the middle of a quiet meadow, fantasy art",
  "A steampunk-inspired mechanical dragon flying over a Victorian city",
  "A photo of a futuristic underwater hotel with glass walls revealing marine life",
  "A surreal painting of a staircase that twists and turns into infinity",
  "A cozy reading nook with a view of a starry night sky, digital art",
  "A futuristic city built on the back of a giant turtle, fantasy art",
  "A whimsical scene of a train traveling through a giant tree, digital art",
  "A photo of a glowing crystal cave with shimmering reflections on the walls",
  "A surreal painting of a floating island with a single tree and a swing hanging from its branch",
  "A futuristic spaceship docked at a spaceport with a bustling alien crowd, sci-fi art",
];
